# Generated by Django 5.2.7 on 2026-03-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ratings',
            new_name='rating',
        ),
    ]
